/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiux.empleado;

import bakend.daos.DaoEmpleado;
import bakend.objetos.Empleado;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class agregarEmpleado extends javax.swing.JPanel {

    private boolean esEdicion = false;
    private Empleado empleadoOriginal;

    /**
     * Creates new form agregarEmpleado
     */
    public agregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tipo_sexo = new javax.swing.JComboBox<>();
        txtNombre5 = new javax.swing.JLabel();
        caja_usuario = new javax.swing.JTextField();
        txtNombre6 = new javax.swing.JLabel();
        caja_nombre = new javax.swing.JTextField();
        txtNombre7 = new javax.swing.JLabel();
        caja_pr_ap = new javax.swing.JTextField();
        txtNombre8 = new javax.swing.JLabel();
        caja_seg_ap = new javax.swing.JTextField();
        txtNombre9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre10 = new javax.swing.JLabel();
        caja_fecha_nac = new javax.swing.JTextField();
        txtNombre11 = new javax.swing.JLabel();
        txtNombre12 = new javax.swing.JLabel();
        caja_num_tel = new javax.swing.JTextField();
        txtNombre13 = new javax.swing.JLabel();
        caja_usuario11 = new javax.swing.JTextField();
        txtNombre14 = new javax.swing.JLabel();
        tipo_puesto = new javax.swing.JComboBox<>();
        caja_usuario7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_agregar_empleado = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tipo_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        txtNombre5.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre5.setText("Nombre Usuario");

        caja_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre6.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre6.setText("Nombre");

        caja_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre7.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre7.setText("Primer Apellido");

        caja_pr_ap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre8.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre8.setText("Segundo Apellido");

        caja_seg_ap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre9.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre9.setText("Sexo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caja_usuario)
                    .addComponent(txtNombre5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caja_nombre)
                    .addComponent(txtNombre7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caja_pr_ap)
                    .addComponent(txtNombre8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caja_seg_ap)
                    .addComponent(txtNombre9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipo_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtNombre5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_pr_ap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_seg_ap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipo_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtNombre10.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre10.setText("Fecha Nacimiento");

        caja_fecha_nac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre11.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre11.setText("Puesto");

        txtNombre12.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre12.setText("No. Telefono");

        caja_num_tel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre13.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre13.setText("Correo");

        caja_usuario11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre14.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        txtNombre14.setText("Contraseña");

        tipo_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agente", "Gerente", "ClienteBase" }));

        caja_usuario7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipo_puesto, 0, 177, Short.MAX_VALUE)
                            .addComponent(caja_num_tel)
                            .addComponent(caja_fecha_nac))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(caja_usuario7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(caja_usuario11))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtNombre10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_fecha_nac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre11)
                .addGap(4, 4, 4)
                .addComponent(tipo_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_num_tel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_usuario11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre14)
                .addGap(2, 2, 2)
                .addComponent(caja_usuario7)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_agregar_empleado.setBackground(new java.awt.Color(242, 242, 242));
        btn_agregar_empleado.setText("AGREGAR");
        btn_agregar_empleado.setBorder(null);
        btn_agregar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_empleadoActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(242, 242, 242));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.setBorder(null);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregar_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btn_eliminar.setBackground(new java.awt.Color(255, 153, 153));
        btn_eliminar.setText("del");
        btn_eliminar.setBorder(null);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("AGREGAR EMPLEADO");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        titulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titulo))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
        ventana.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_agregar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_empleadoActionPerformed
        java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
        titulo.setText("AGREGAR EMPLEADO");
        // Después: solo mostrar si es edición
        btn_eliminar.setVisible(esEdicion);

        String usuario = caja_usuario.getText().trim();
        String nombre = caja_nombre.getText().trim();
        String prAp = caja_pr_ap.getText().trim();
        String segAp = caja_seg_ap.getText().trim();
        String sexo = tipo_sexo.getSelectedItem().toString();
        String fecha = caja_fecha_nac.getText(); // "yyyy-MM-dd"
        String puesto = tipo_puesto.getSelectedItem().toString();
        String telefono = caja_num_tel.getText().trim();
        String correo = caja_usuario11.getText().trim();
        String contrasena = caja_usuario7.getText().trim();

        if ("Mujer".equals(sexo)) {
            sexo = "F";
        } else {
            sexo = "M";
        }
        // Revisar que no haya campos vacíos
        if (usuario.isEmpty() || nombre.isEmpty() || prAp.isEmpty() || segAp.isEmpty()
                || fecha.isEmpty() || telefono.isEmpty() || correo.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
            return;
        }

        if (usuario.length() > 6) {
            JOptionPane.showMessageDialog(this, "Usuario: Maximo 6 caracteres");
        }

        // Validar que solo contengan letras
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras");
            return;
        }

        if (!prAp.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this, "El primer apellido solo puede contener letras");
            return;
        }

        if (!segAp.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this, "El segundo apellido solo puede contener letras");
            return;
        }

        // Validar fecha
        LocalDate fechaNac;
        try {
            fechaNac = LocalDate.parse(fecha); // formato YYYY-MM-DD
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese una fecha válida (AAAA-MM-DD)");
            return;
        }

        // Verificar que no sea superior a hoy
        if (fechaNac.isAfter(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede ser superior a la fecha actual");
            return;
        }

        // Validar teléfono (solo números y longitud 10)
        if (!telefono.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de teléfono válido (solo dígitos)");
            return;
        }

        if (telefono.length() != 10) {
            JOptionPane.showMessageDialog(this, "El número de teléfono debe tener 10 dígitos");
            return;
        }

        // Validar correo
        if (!correo.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$")) {
            JOptionPane.showMessageDialog(this, "Ingrese un correo válido");
            return;
        }

        String regexContrasena = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[!@#$%^&*()\\-+=]).{8,}$";

        if (!contrasena.matches(regexContrasena)) {
            JOptionPane.showMessageDialog(this,
                    "La contraseña debe tener al menos:\n"
                    + "- 1 letra\n"
                    + "- 1 número\n"
                    + "- 1 carácter especial (!@#$%^&*()-+=)\n"
                    + "- Mínimo 8 caracteres");
            return;
        }

        // Si todo está bien, crear el objeto Empleado
        Empleado emp = new Empleado();
        emp.setIdEmpleado(usuario);
        emp.setSuperEmpleado("EMP001");
        emp.setNombre(nombre);
        emp.setPrimerAp(prAp);
        emp.setSegundoAp(segAp);
        emp.setSexo(sexo);
        java.sql.Date sqlDate = java.sql.Date.valueOf(fecha); // convierte a java.sql.Date
        emp.setFechaNac(sqlDate); // cambia el tipo de la propiedad fechaNac a java.sql.Date
        emp.setPuesto(puesto);
        emp.setNumTel(telefono);
        emp.setCorreo(correo);
        emp.setContrasena(contrasena);

        // Llamar al DAO para guardar en BD
        DaoEmpleado dao = new DaoEmpleado();
        try {
            if (esEdicion) {
                // Mantener el mismo ID
                emp.setIdEmpleado(empleadoOriginal.getIdEmpleado());
                dao.actualizarEmpleado(emp);
                JOptionPane.showMessageDialog(this, "Empleado actualizado correctamente");
            } else {
                dao.insertarEmpleado(emp);  // <-- Aquí se corrige
                JOptionPane.showMessageDialog(this, "Empleado agregado correctamente");
            }
            ventana.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_btn_agregar_empleadoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar este empleado?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // Si el usuario elige "Sí"
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                DaoEmpleado dao = new DaoEmpleado();
                String idEmpleado = caja_usuario.getText().trim(); // o el ID que tengas seleccionado
                dao.eliminarEmpleado(idEmpleado); // método que borre de la BD
                JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente");

                // Opcional: cerrar ventana o limpiar campos
                java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
                ventana.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    public agregarEmpleado(Empleado emp) {
        initComponents();
        esEdicion = true;
        empleadoOriginal = emp;
        btn_eliminar.setVisible(true);

        titulo.setText("MODIFICAR");
        // Llenar los campos como ya lo tienes
        caja_usuario.setText(emp.getIdEmpleado());
        caja_nombre.setText(emp.getNombre());
        caja_pr_ap.setText(emp.getPrimerAp());
        caja_seg_ap.setText(emp.getSegundoAp());
        tipo_sexo.setSelectedItem(emp.getSexo().equalsIgnoreCase("F") ? "Mujer" : "Hombre");
        caja_fecha_nac.setText(emp.getFechaNac().toString());
        tipo_puesto.setSelectedItem(emp.getPuesto());
        caja_num_tel.setText(emp.getNumTel());
        caja_usuario11.setText(emp.getCorreo());
        caja_usuario7.setText(emp.getContrasena());

        caja_usuario.setEditable(false);
        // Si es edición, cambiar texto del botón
        btn_agregar_empleado.setText("GUARDAR CAMBIOS");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_empleado;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JTextField caja_fecha_nac;
    private javax.swing.JTextField caja_nombre;
    private javax.swing.JTextField caja_num_tel;
    private javax.swing.JTextField caja_pr_ap;
    private javax.swing.JTextField caja_seg_ap;
    private javax.swing.JTextField caja_usuario;
    private javax.swing.JTextField caja_usuario11;
    private javax.swing.JTextField caja_usuario7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> tipo_puesto;
    private javax.swing.JComboBox<String> tipo_sexo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtNombre10;
    private javax.swing.JLabel txtNombre11;
    private javax.swing.JLabel txtNombre12;
    private javax.swing.JLabel txtNombre13;
    private javax.swing.JLabel txtNombre14;
    private javax.swing.JLabel txtNombre5;
    private javax.swing.JLabel txtNombre6;
    private javax.swing.JLabel txtNombre7;
    private javax.swing.JLabel txtNombre8;
    private javax.swing.JLabel txtNombre9;
    // End of variables declaration//GEN-END:variables
}
